package registry

var RegistryMigrations = []string{
	`create table if not exists workflow_candidates (
  id text primary key,
  project_id text not null,
  source text not null,
  task text not null,
  start_url text not null,
  recipe_draft json not null,
  status text not null,
  searchable boolean not null default false,
  created_at text not null,
  reviewed_at text
)`,
	`create table if not exists workflow_recipes (
  id text primary key,
  project_id text not null,
  site text not null,
  intent text not null,
  status text not null,
  searchable boolean not null default false,
  current_version integer not null,
  recipe json not null
)`,
	`create table if not exists workflow_outbox (
  id text primary key,
  type text not null,
  idempotency_key text not null,
  payload json not null,
  status text not null,
  created_at text not null,
  processed_at text
	)`,
}

var PostgresMigrations = []string{
	`create extension if not exists pgcrypto`,
	`create extension if not exists vector`,
	`create table if not exists workflow_candidates (
  id text primary key,
  project_id text not null,
  source text not null,
  status text not null,
  created_at timestamptz not null default now(),
  payload jsonb not null
)`,
	`create table if not exists workflow_recipes (
  id text primary key,
  project_id text not null,
  site text not null,
  status text not null,
  searchable boolean not null default false,
  current_version integer not null default 1,
  risk_level text not null default 'read_only',
  description varchar(500) not null default '',
  recipe_json jsonb not null default '{}'::jsonb,
  embedding vector(1024),
  updated_at timestamptz not null default now(),
  payload jsonb not null
)`,
	`create table if not exists workflow_versions (
  workflow_id text not null,
  version integer not null,
  change_summary varchar(500) not null default '',
  created_from_task_run_id text not null default '',
  created_at timestamptz not null default now(),
  payload jsonb not null,
  primary key (workflow_id, version)
)`,
	`create table if not exists workflow_runs (
  id text primary key,
  project_id text not null,
  workflow_id text not null,
  version integer not null,
  created_at timestamptz not null default now(),
  payload jsonb not null
)`,
	`create table if not exists task_runs (
  id text primary key,
  project_id text not null,
  site text not null,
  task_template text not null default '',
  summary varchar(500) not null default '',
  original_path jsonb not null default '[]'::jsonb,
  optimized_path jsonb not null default '[]'::jsonb,
  memory_context_id text not null default '',
  memory_evidence_refs jsonb not null default '[]'::jsonb,
  status text not null,
  created_at timestamptz not null default now(),
  payload jsonb not null,
  constraint task_runs_summary_length check (char_length(coalesce(payload->>'summary', '')) <= 500)
)`,
	`create table if not exists action_steps (
  id text primary key,
  task_run_id text not null references task_runs(id) on delete cascade,
  page_state_id text not null default '',
  step_index integer not null,
  action_type text not null,
  target_name text not null default '',
  value_template text not null default '',
  reasoning_summary varchar(500) not null default '',
  result_summary varchar(500) not null default '',
  is_branch_noise boolean not null default false,
  created_at timestamptz not null default now(),
  payload jsonb not null default '{}'::jsonb
)`,
	`create table if not exists site_task_guides (
  id text primary key,
  project_id text not null,
  site text not null,
  module text not null default '',
  task_intent_key text not null,
  task_intent_summary varchar(500) not null default '',
  task_intent_terms jsonb not null default '{}'::jsonb,
  task_examples jsonb not null default '[]'::jsonb,
  input_schema jsonb not null default '[]'::jsonb,
  route_scope jsonb not null default '{}'::jsonb,
  start_url_pattern text not null default '',
  start_page_guard jsonb not null default '{}'::jsonb,
  page_guards jsonb not null default '[]'::jsonb,
  ui_state_entries jsonb not null default '[]'::jsonb,
  steps jsonb not null default '[]'::jsonb,
  abandon_rules jsonb not null default '[]'::jsonb,
  reject_rules jsonb not null default '[]'::jsonb,
  variable_rules jsonb not null default '[]'::jsonb,
  evidence jsonb not null default '[]'::jsonb,
  summary varchar(500) not null default '',
  confidence double precision not null default 0,
  success_count integer not null default 0,
  abandoned_count integer not null default 0,
  misleading_count integer not null default 0,
  unused_count integer not null default 0,
  stale_count integer not null default 0,
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  payload jsonb not null default '{}'::jsonb,
  unique (project_id, site, module, task_intent_key)
)`,
	`create table if not exists site_task_guide_feedback (
  id text primary key,
  guide_id text not null,
  state_id text not null default '',
  task_run_id text not null default '',
  context_id text not null default '',
  label text not null,
  reason varchar(500) not null default '',
  matched_step_count integer not null default 0,
  backtrack_count integer not null default 0,
  created_at timestamptz not null default now(),
  payload jsonb not null default '{}'::jsonb
)`,
	`create index if not exists idx_site_task_guides_scope on site_task_guides(project_id, site, module, status, updated_at)`,
	`create index if not exists idx_site_task_guides_page_guards on site_task_guides using gin(page_guards)`,
	`alter table if exists site_task_guides add column if not exists task_intent_terms jsonb not null default '{}'::jsonb`,
	`alter table if exists site_task_guides add column if not exists input_schema jsonb not null default '[]'::jsonb`,
	`alter table if exists site_task_guides add column if not exists route_scope jsonb not null default '{}'::jsonb`,
	`alter table if exists site_task_guides add column if not exists ui_state_entries jsonb not null default '[]'::jsonb`,
	`alter table if exists site_task_guides add column if not exists reject_rules jsonb not null default '[]'::jsonb`,
	`alter table if exists site_task_guide_feedback add column if not exists state_id text not null default ''`,
	`create table if not exists page_states (
  id text primary key,
  project_id text not null,
  site text not null,
  url_pattern text not null default '',
  page_name text not null default '',
  purpose_summary varchar(500) not null default '',
  hard_rules jsonb not null default '{}'::jsonb,
  required_controls jsonb not null default '[]'::jsonb,
  required_text jsonb not null default '[]'::jsonb,
  embedding vector(1024),
  status text not null,
  updated_at timestamptz not null default now(),
  payload jsonb not null
)`,
	`create table if not exists page_transitions (
  id text primary key,
  project_id text not null,
  site text not null,
  from_page_state text not null,
  to_page_state text not null,
  workflow_id text not null default '',
  version integer not null default 0,
  chunk_id text not null default '',
  action_name text not null default '',
  target_name text not null default '',
  target_candidates jsonb not null default '{}'::jsonb,
  guard_rules jsonb not null default '{}'::jsonb,
  risk_level text not null default 'read_only',
  success_count integer not null default 0,
  failure_count integer not null default 0,
  disabled_at timestamptz,
  payload jsonb not null
)`,
	`create table if not exists site_manual_sources (
  id text primary key,
  project_id text not null,
  site text not null,
  module text not null default '',
  title text not null default '',
  source_type text not null,
  content_hash text not null,
  raw_content text not null,
  metadata jsonb not null default '{}'::jsonb,
  status text not null default 'active',
  created_at timestamptz not null default now(),
  payload jsonb not null default '{}'::jsonb,
  unique (project_id, site, module, content_hash)
)`,
	`create table if not exists site_manual_wiki_pages (
  id text primary key,
  project_id text not null,
  site text not null,
  module text not null default '',
  page_key text not null,
  title text not null default '',
  summary varchar(500) not null default '',
  facts jsonb not null default '[]'::jsonb,
  procedures jsonb not null default '[]'::jsonb,
  related_pages jsonb not null default '[]'::jsonb,
  source_refs jsonb not null default '[]'::jsonb,
  confidence double precision not null default 0,
  status text not null default 'active',
  updated_at timestamptz not null default now(),
  payload jsonb not null default '{}'::jsonb,
  unique (project_id, site, module, page_key)
)`,
	`create table if not exists site_manual_wiki_chunks (
  id text primary key,
  wiki_page_id text not null,
  project_id text not null,
  site text not null,
  module text not null default '',
  chunk_type text not null,
  text varchar(500) not null,
  page_guards jsonb not null default '{}'::jsonb,
  target_terms jsonb not null default '[]'::jsonb,
  source_refs jsonb not null default '[]'::jsonb,
  embedding jsonb,
  status text not null default 'active',
  payload jsonb not null default '{}'::jsonb
)`,
	`create index if not exists idx_site_manual_sources_scope on site_manual_sources(project_id, site, module, status, created_at)`,
	`create index if not exists idx_site_manual_pages_scope on site_manual_wiki_pages(project_id, site, module, status, updated_at)`,
	`create index if not exists idx_site_manual_chunks_scope on site_manual_wiki_chunks(project_id, site, module, status)`,
	`create index if not exists idx_site_manual_chunks_page_guards on site_manual_wiki_chunks using gin(page_guards)`,
	`create index if not exists idx_site_manual_chunks_target_terms on site_manual_wiki_chunks using gin(target_terms)`,
	`create index if not exists idx_site_manual_chunks_source_refs on site_manual_wiki_chunks using gin(source_refs)`,
	`create table if not exists page_surfaces (
	  id text primary key,
	  project_id text not null,
	  site text not null,
	  parent_page_state_id text not null,
	  surface_type text not null default 'unknown',
	  surface_fingerprint text not null default '',
	  title text not null default '',
	  required_text jsonb not null default '[]'::jsonb,
	  required_controls jsonb not null default '[]'::jsonb,
	  visibility_rules jsonb not null default '{}'::jsonb,
	  observation_count integer not null default 1,
	  status text not null default 'active',
	  first_seen_at timestamptz not null default now(),
	  last_seen_at timestamptz,
	  payload jsonb not null
	)`,
	`create table if not exists page_observation_events (
  id text primary key,
  project_id text not null,
  site text not null,
  url text not null default '',
  url_pattern text not null default '',
  title text not null default '',
  visible_text_sample varchar(500) not null default '',
  controls jsonb not null default '[]'::jsonb,
  links jsonb not null default '[]'::jsonb,
  fingerprint text not null default '',
  created_at timestamptz not null default now(),
  last_seen_at timestamptz,
  seen_count integer not null default 1,
  payload jsonb not null
)`,
	`create table if not exists experience_memories (
  id text primary key,
  project_id text not null,
  site text not null,
  task_template text not null default '',
  intent text not null default '',
  summary varchar(500) not null default '',
  start_page_state text not null default '',
  end_page_state text not null default '',
  optimized_path jsonb not null default '[]'::jsonb,
  steps_summary jsonb not null default '[]'::jsonb,
  variables jsonb not null default '[]'::jsonb,
  success_count integer not null default 0,
  failure_count integer not null default 0,
  last_success_at timestamptz,
  last_failure_at timestamptz,
  failure_warnings jsonb not null default '[]'::jsonb,
  searchable boolean not null default false,
  review_status text not null default 'pending_review',
  embedding vector(1024),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  payload jsonb not null
)`,
	`create table if not exists failure_memories (
  id text primary key,
  experience_id text not null default '',
  project_id text not null,
  site text not null,
  page_state_id text not null default '',
  action_name text not null default '',
  failure_type text not null default '',
  failure_summary varchar(500) not null default '',
  avoid_hint varchar(500) not null default '',
  created_at timestamptz not null default now(),
  last_seen_at timestamptz,
  occurrence_count integer not null default 1,
  payload jsonb not null
)`,
	`create table if not exists memory_context_events (
  id text primary key,
  project_id text not null,
  task text not null default '',
  current_url text not null default '',
  current_page_state text not null default '',
  selected_experience_ids jsonb not null default '[]'::jsonb,
  selected_workflow_ids jsonb not null default '[]'::jsonb,
  evidence_refs jsonb not null default '[]'::jsonb,
  recommended_mode text not null default 'normal',
  created_at timestamptz not null default now(),
  payload jsonb not null
)`,
	`create table if not exists memory_attribution_events (
  id text primary key,
  project_id text not null,
  site text not null,
  task_run_id text not null default '',
  context_id text not null default '',
  evidence_id text not null,
  evidence_source text not null,
  label text not null,
  reason varchar(500) not null default '',
  signals jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  payload jsonb not null
)`,
	`create table if not exists memory_evidence_stats (
  project_id text not null,
  site text not null default '',
  evidence_id text not null,
  evidence_source text not null,
  helpful_count integer not null default 0,
  unused_count integer not null default 0,
  misleading_count integer not null default 0,
  stale_count integer not null default 0,
  neutral_count integer not null default 0,
  utility_score double precision not null default 0,
  last_feedback_at timestamptz,
  payload jsonb not null,
  primary key (project_id, evidence_source, evidence_id)
)`,
	`create table if not exists memory_reviews (
  id text primary key,
  project_id text not null,
  target_type text not null,
  target_id text not null,
  status text not null,
  summary varchar(500) not null default '',
  created_at timestamptz not null default now(),
  reviewed_at timestamptz,
  payload jsonb not null
)`,
	`create table if not exists selector_stats (
  key text primary key,
  workflow_id text not null,
  version integer not null,
  payload jsonb not null
)`,
	`create table if not exists interrupt_handlers (
  id text primary key,
  project_id text not null,
  site text not null,
  status text not null,
  payload jsonb not null
)`,
	`create table if not exists repair_patches (
  id text primary key,
  project_id text not null,
  workflow_id text not null,
  status text not null,
  created_at timestamptz not null default now(),
  payload jsonb not null
)`,
	`create table if not exists workflow_outbox (
  id text primary key,
  type text not null,
  idempotency_key text not null unique,
  status text not null,
  created_at timestamptz not null default now(),
  payload jsonb not null
)`,
	`create table if not exists outbox_events (
  id text primary key,
  type text not null,
  idempotency_key text not null unique,
  status text not null,
  created_at timestamptz not null default now(),
  payload jsonb not null
)`,
	`alter table workflow_recipes add column if not exists embedding vector(1024)`,
	`alter table page_states add column if not exists hard_rules jsonb not null default '{}'::jsonb`,
	`alter table page_states add column if not exists embedding vector(1024)`,
	`alter table page_transitions add column if not exists workflow_id text not null default ''`,
	`alter table page_transitions add column if not exists version integer not null default 0`,
	`alter table page_transitions add column if not exists chunk_id text not null default ''`,
	`alter table page_transitions add column if not exists action_name text not null default ''`,
	`alter table page_transitions add column if not exists target_name text not null default ''`,
	`alter table page_transitions add column if not exists target_candidates jsonb not null default '{}'::jsonb`,
	`alter table page_transitions add column if not exists guard_rules jsonb not null default '{}'::jsonb`,
	`alter table page_transitions add column if not exists risk_level text not null default 'read_only'`,
	`alter table page_observation_events add column if not exists last_seen_at timestamptz`,
	`alter table page_observation_events add column if not exists seen_count integer not null default 1`,
	`alter table failure_memories add column if not exists last_seen_at timestamptz`,
	`alter table failure_memories add column if not exists occurrence_count integer not null default 1`,
	`alter table memory_context_events add column if not exists evidence_refs jsonb not null default '[]'::jsonb`,
	`alter table task_runs add column if not exists memory_context_id text not null default ''`,
	`alter table task_runs add column if not exists memory_evidence_refs jsonb not null default '[]'::jsonb`,
	`create index if not exists idx_workflow_candidates_project_status on workflow_candidates(project_id, status)`,
	`create index if not exists idx_workflow_recipes_active on workflow_recipes(project_id, site, status, searchable)`,
	`create index if not exists idx_workflow_recipes_risk_updated on workflow_recipes(risk_level, updated_at)`,
	`create index if not exists idx_workflow_recipes_recipe_json on workflow_recipes using gin(recipe_json)`,
	`create index if not exists idx_workflow_recipes_embedding on workflow_recipes using hnsw (embedding vector_cosine_ops)`,
	`create index if not exists idx_workflow_recipes_payload on workflow_recipes using gin(payload)`,
	`create index if not exists idx_action_steps_task_run on action_steps(task_run_id, step_index)`,
	`create index if not exists idx_task_runs_project_site on task_runs(project_id, site, status)`,
	`create index if not exists idx_page_states_project_site on page_states(project_id, site, status)`,
	`create index if not exists idx_page_states_updated on page_states(updated_at)`,
	`create index if not exists idx_page_states_hard_rules on page_states using gin(hard_rules)`,
	`create index if not exists idx_page_states_embedding on page_states using hnsw (embedding vector_cosine_ops)`,
	`create index if not exists idx_page_states_payload on page_states using gin(payload)`,
	`create index if not exists idx_page_surfaces_lookup on page_surfaces(project_id, site, parent_page_state_id, surface_type)`,
	`create index if not exists idx_page_surfaces_payload on page_surfaces using gin(payload)`,
	`create index if not exists idx_page_transitions_lookup on page_transitions(project_id, site, from_page_state, to_page_state)`,
	`create index if not exists idx_page_observation_events_lookup on page_observation_events(project_id, site, url_pattern, created_at)`,
	`create index if not exists idx_page_observation_events_controls on page_observation_events using gin(controls)`,
	`create index if not exists idx_experience_memories_filter on experience_memories(project_id, site, review_status, searchable, updated_at)`,
	`create index if not exists idx_experience_memories_start_page on experience_memories(project_id, site, start_page_state)`,
	`create index if not exists idx_experience_memories_steps on experience_memories using gin(steps_summary)`,
	`create index if not exists idx_experience_memories_variables on experience_memories using gin(variables)`,
	`create index if not exists idx_experience_memories_embedding on experience_memories using hnsw (embedding vector_cosine_ops)`,
	`create index if not exists idx_experience_memories_payload on experience_memories using gin(payload)`,
	`create index if not exists idx_failure_memories_filter on failure_memories(project_id, site, page_state_id, created_at)`,
	`create index if not exists idx_memory_context_events_lookup on memory_context_events(project_id, current_page_state, created_at)`,
	`create index if not exists idx_memory_context_events_payload on memory_context_events using gin(payload)`,
	`create index if not exists idx_memory_attribution_task_context on memory_attribution_events(project_id, task_run_id, context_id, created_at)`,
	`create index if not exists idx_memory_attribution_evidence on memory_attribution_events(project_id, evidence_source, evidence_id, created_at)`,
	`create index if not exists idx_memory_evidence_stats_score on memory_evidence_stats(project_id, site, utility_score desc, last_feedback_at desc)`,
	`create index if not exists idx_memory_reviews_filter on memory_reviews(project_id, target_type, status, created_at)`,
}
